// web-app/src/components/modals/createTransaction.tsx
import './modals.css'
import {type JSX, useState} from "react";
import type {IProject, ITransaction} from "../../interfaces.ts";
import {ModalWrapper} from "./wrapper.tsx";

export interface createTransactionProps {
    modalOpen: boolean,
    closeModal: () => void,
    transactionRefetch: () => void,
    project: IProject,
}

export function CreateExpenseModal({props}: { props: createTransactionProps }): JSX.Element {
    const [description, setDescription] = useState<string>("")
    const [amount, setAmount] = useState<string>("-20")
    const amountAsNumber: number = Number(amount)

    const [error, setError] = useState<string>("")

    async function submitTransaction() {
        const expense: ITransaction = {
            id: 0,
            project_id: props.project.id,
            description: description,
            amount: amountAsNumber,
            date: new Date(),
        }
        const response = await fetch("/api/transaction", {method: "POST", body: JSON.stringify(expense)})
        const data = await response.json()
        if (!response.ok) {
            setError(data)
            return
        }
        props.closeModal()
        props.transactionRefetch()
    }

    return (
        <ModalWrapper modalOpen={props.modalOpen} closeModal={props.closeModal}>
            <p className={error == "" ? "hidden" : ""}>{error}</p>
            <div className={"w-full flex justify-between items-start"}>
                <h1 className={"modalHeading"}>Add Expense</h1>
                <button className={"cursor-pointer hover:text-white duration-150 scale-105"} onClick={() => props.closeModal()}>x
                </button>
            </div>
            <label htmlFor="">Description</label>
            <input type="text" placeholder={"Bluray"} onChange={(e) => setDescription(e.target.value)}/>
            <label htmlFor="">Amount</label>
            <input type="number" max={0} value={amount}
                   onChange={(e) => Number(e.target.value) <= 0 && setAmount(e.target.value)}/>
            <label htmlFor="">Date</label>
            <input type="date" onChange={(e) => setAmount(e.target.value)}/>
            <div className={"flex gap-4 justify-end mt-8"}>
                <button className={"button"} onClick={() => props.closeModal()}>Cancel</button>
                <button className={"button"} onClick={() => submitTransaction()}>Add Expense</button>
            </div>
        </ModalWrapper>
    )
}

export function CreateIncomeModal({props}: { props: createTransactionProps }): JSX.Element {
    const [description, setDescription] = useState<string>("")
    const [amount, setAmount] = useState<string>("20")
    const amountAsNumber: number = Number(amount)

    const [error, setError] = useState<string>("")

    async function submitIncome() {
        const income: ITransaction = {
            id: 0,
            project_id: props.project.id,
            description: description,
            amount: amountAsNumber,
            date: new Date(),
        }
        const response = await fetch("/api/transaction", {method: "POST", body: JSON.stringify(income)})
        const data = await response.json()
        if (!response.ok) {
            setError(data)
            return
        }
        props.closeModal()
        props.transactionRefetch()
    }

    return (
        <ModalWrapper modalOpen={props.modalOpen} closeModal={props.closeModal}>
            <p className={error == "" ? "hidden" : ""}>{error}</p>
            <div className={"w-full flex justify-between items-start"}>
                <h1 className={"modalHeading"}>Add Income</h1>
                <button className={"cursor-pointer hover:text-white duration-150 scale-105"} onClick={() => props.closeModal()}>x
                </button>
            </div>
            <label htmlFor="">Description</label>
            <input type="text" placeholder={"Special Funds"} onChange={(e) => setDescription(e.target.value)}/>
            <label htmlFor="">Amount</label>
            <input type="number" min={0} value={amount}
                   onChange={(e) => Number(e.target.value) >= 0 && setAmount(e.target.value)}/>
            <label htmlFor="">Date</label>
            <input type="date" onChange={(e) => setAmount(e.target.value)}/>
            <div className={"flex gap-4 justify-end mt-8"}>
                <button className={"button"} onClick={() => props.closeModal()}>Cancel</button>
                <button className={"button"} onClick={() => submitIncome()}>Add Income</button>
            </div>
        </ModalWrapper>
    )
}

// solid-web/src/components/models/createTransaction.tsx
import {createMemo, createSignal} from "solid-js";
import {ITransaction} from "../../interfaces";

export interface ITransactionProps {
    open: boolean,
    toggle: () => void,
    projectId: number
}

export function CreateTransaction(props: ITransactionProps) {
    const [description, setDescription] = createSignal<string>("")
    const [amount, setAmount] = createSignal<string>("0")
    const [date, setDate] = createSignal<Date>(new Date())

    const amountAsNumber = createMemo(() => Number(amount()))

    async function submitTransaction() {
        const body: ITransaction = {
            id: 0,
            project_id: props.projectId,
            description: description(),
            amount: amountAsNumber(),
            date: date()
        }
        const response = await fetch(`/api/project/${props.projectId}/transaction`, {
            method: "POST",
            body: JSON.stringify(body)
        })
        if (!response.ok) {
            // TODO: add Error Notification
            return
        }
        props.toggle()
    }

    return (
        <div
            class={[`fixed w-screen h-screen top-0 left-0 z-10 bg-black/50 flex items-center justify-center`, props.open ? "block" : "hidden"]}
            onClick={() => props.toggle()}>
            <div class={"w-fit h-fit flex flex-col rounded-xl border border-border bg-surface p-5 shadow-sm"}
                 onClick={(event) => event.stopPropagation()}>
                <header class="border-b border-border px-6 py-5">
                    <div class="flex items-center justify-between gap-4">
                        <div class="min-w-0">
                            <div class="flex items-center gap-4">
                                <h2 class="mb-0 truncate text-xl font-semibold">
                                    Add Transaction
                                </h2>
                            </div>

                            <p class="mb-0 px-0 mt-1 text-sm text-start text-foreground/50">
                                Create a new Transaction by filling the required Fields
                            </p>
                        </div>
                    </div>
                </header>
                <div class={"flex flex-col gap-4 mt-4"}>
                    <label>Description
                        <input type="text" placeholder={"Stuff in my Rack"} value={description()}
                               onChange={(e) => setDescription(e.target.value)}/>
                    </label>
                    <label>
                        Amount
                        <div class="relative">
                            <span class="absolute left-3 top-1/2 -translate-y-1/2 text-sm text-foreground/40">
                                €
                            </span>
                            <input
                                type="number"
                                min="0"
                                step="0.01"
                                value={amount()}
                                placeholder="20"
                                class={"pl-8"}
                                onInput={(event) =>
                                    setAmount(event.currentTarget.value)
                                }
                            />
                        </div>
                    </label>
                    <label>
                        <input type="date" defaultValue={date().toDateString()}
                               onChange={(e) => setDate(e.currentTarget.valueAsDate as Date)}/>
                    </label>
                </div>
                <div class={"flex gap-4 justify-end mt-8"}>
                    <button class={"button"} onClick={() => submitTransaction()}>Add Transaction</button>
                </div>
            </div>
        </div>
    )
}
